[Feat/#142] 획득 쿠폰 뷰 UI
Team-Offroad/Offroad-iOS pull request #155
Opened 2024-09-05 08:56 UTC by codeJiwon

### 🌴 작업한 브랜치
- #142 

### ✅ 작업한 내용

획득 쿠폰 뷰 커스텀 segmentControl 적용
쿠폰 상세 뷰 디자인 및 레이아웃 적용
사용하기 버튼 눌렀을 때 코드 입력 팝업 뷰 뜨게 구현

### ❗️PR Point

### 📸 스크린샷

![Simulator Screen Recording - iPhone 15 Pro - 2024-09-05 at 17 49 37](https://github.com/user-attachments/assets/740d636b-11c2-4e76-bf00-8c22796c848b)

|뷰|설명|
|:------:|:---:|
|  CouponDetailView      |  쿠폰 상세 뷰 UI 요소   |
|  CouponDetailViewController      |  쿠폰 상세 뷰 뷰컨트롤러   |
|  CouponUsagePopupView      |  쿠폰 코드 입력하는 뷰   |

- Resolved: #142

2024-09-05 09:54 UTC, Johyerin reviewed
전체적으로 컨벤션 확인해주시면 좋을 것 같고 여유 되실 때 천천히 고쳐주셔도 될 것 같아요!
리뷰 내용 수정보다는 UI/UX상으로 구현이 아직 덜 된 부분이 보이는 것 같아서 QA 전에 후딱 구현해야 할 것 같습니다! 
- segmentControl이 초기 상태에 하이라이트 되어있지 않은 것
- 사용 가능, 사용 완료 선택에 따른 컬렉션 뷰 업데이트
- 커스텀 백 버튼 구현
요 부분들 추가 구현 필요할 것 같습니다 ㅜㅜ

컬렉션 뷰 같은 경우에는 서버 붙이면서 진행하는게 오히려 편할 수도 있을 것 같아서 새로 이슈 파서 진행해주셔도 좋을 것 같습니다!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_coupon.imageset/🎫.svg
P1

image asset의 파일명이 영문이 아니면 추후에 오류가 발생할 수도 있기 때문에 영문으로 된 이름의 파일로 다시 넣어주는 게 좋을 것 같아요!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_key.imageset/Contents.json
> +    "version" : 1
P3

svg 파일로 추출한 경우에는 사진과 같이 우측 메뉴에서 Scales를 single로 변경해주세요! (이 에셋 말고 다른 에셋들도 individual로 되어있는 것 같아서 일괄적으로 변경 부탁드립니당)

<img width="191" alt="image" src="https://github.com/user-attachments/assets/f7bfddd5-4102-4a2b-8a98-003c374a45ef">

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AcquiredCouponCell.swift
> +        $0.clipsToBounds = true
P2

extension의 roundCorners활용하는 게 더 깔끔할 것 같아요!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AcquiredCouponCell.swift
> +
P1

UI요소는 컨벤션에 맞게 UI Properties로 작성해 주세용

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AcquiredCouponCell.swift
> +    }
P2

1줄의 텍스트의 경우에는 따로 적어주지 않아도 될 것 같습니다!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AcquiredCouponCell.swift
> +    }
newBadgeView를 사용해서 image를 불러왔음에도 Label을 생성하신 이유가 있으실까요?

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AcquiredCouponCell.swift
> +        setupLayout()
P1

컨벤션에 맞게 super 메소드 아래 한 줄 띄워주세욥

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AcquiredCouponCell.swift
> +        contentView.clipsToBounds = true
P2

여기도 extension의 roundCorners활용하는 게 더 좋을 것 같아요!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AcquiredCouponCell.swift
> +
P1

contentView의 속성을 지정하는 부분은 setupStyle() 함수로 빼서 작성해주시면 좋을 것 같습니다!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/AcquiredCouponView.swift
> +
P1

여기도 주석 수정해주세용

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
> +    }
P2

여기 두 개도 roundCorners 활용해서 써주면 좋을 것 같아요

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
> +            couponDetailView,
P1

함수명 컨벤션에 맞게 수정해주시고 `backgroundColor = UIColor.primary(.listBg)`요 코드는 setupStyle() 함수로 따로 빼주세요!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponUsagePopupView.swift
> +    }
P1

필요없는 주석이라면 지워주세요!

2024-09-05 09:54 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponUsagePopupView.swift
> +        }
P1

왼쪽에 패딩값 필요할 것 같은데 extension 활용해서 추가해주세요!

2024-09-05 10:51 UTC, nolanMinsung requested changes
수고하셨습니다!
앞선 리뷰에 더해서 다음 문제들도 추가로 해결하면 될 것 같습니다. 
- 팝업 뷰가 터치되지 않는 문제 해결
- 마이페이지 화면에서 획득 쿠폰 뷰로 넘어가는 코드 작성
- 탭바 숨기는 코드 작성
그러면 기능상으로는 큰 문제 없을 것 같아요!

2024-09-05 10:51 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
> +    }
P1
팝업 뷰에서 X버튼과 텍스트필드가 터치를 인식하지 못하는 것 같습니다.
아마 팝업 뷰가 뷰 컨트롤러의 계층 구조상 가장 아래에 위치하는 것 때문으로 보입니다. 
popupView가 addSubviews() 메서드 매개변수로 가장 먼저 적혀있는데, 
addSubview한 순서대로 아래에서 차곡차곡 쌓인다고 생각하시면 될 것 같습니다!
(아마 popupView를 addSubviews 매개변수 중 가장 마지막으로 입력하면 되겠지요?)

P3
쿠폰 사용하기 버튼을 누를 경우 새로운 뷰컨트롤러를 present하는 방식이 아닌 기존의 뷰를 숨기고 있다가 나타내는 방법으로 구현하는 것 같아 보입니다~
개인적으로는 새로운 뷰컨트롤러를 생성하여 present하는 방법이 훨씬 매끄럽고 유용할 것 같습니다 :)
우선 QA까지는 팝업 방식을 유지하고 추후에 팝업을 편하게 사용할 수 있도록 공통 컴포넌트로 제가 구현해 볼게요!~

2024-09-05 10:51 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
> +
P2
현재 마이페이지 화면에서 획득 쿠폰 셀을 눌렀을 때 획득 쿠폰 뷰가 push 되도록 구현되어있지 않은 것 같습니다~  
이는 MypageViewController의 collectionView(_:didSelectItemAt:) 메서드에서 구현해주시면 될 것 같아요  
또한, 화면이 push될 때(화면이 나타날 때) 탭바가 사라지도록 구현하는 코드 역시 구현해주시면 될 것 같습니다 :)
탭바를 숨기는 코드는 SettingsViewController의 viewWillAppear(_:)  메서드를 참고하시면 될 것 같습니다!

2024-09-07 05:21 UTC, nolanMinsung approved these changes
수고하셨습니다!! 👍

2024-09-07 10:33 UTC, merged