[Fix] #172 - 획득 쿠폰 상세 뷰UI 개선
Team-Offroad/Offroad-iOS pull request #179
Opened 2024-09-14 15:03 UTC by nolanMinsung

### 🌴 작업한 브랜치
- #172 

### ✅ 작업한 내용

쿠폰 코드 상세 뷰 및, 쿠폰 코드 입력 팝업 뷰의 UI를 개선하였습니다. 

팝업이 뜰 때의 로직을 개선하였습니다. 
- 기존 코드: 새로운 뷰컨트롤러를 present하지 않고, 기존의 popupView를 숨김처리하였다가, '사용하기' 버튼을 누르면 popupView가 보이도록 설정한 상황이었습니다.
- 바뀐 코드: '사용하기' 버튼을 누르면 팝업을 보여주는 새로운 뷰컨트롤러가 present되도록 구현하였습니다.
  - present되는 새로운 뷰컨트롤러는 `CouponCodeInputPopupViewController`입니다. 
  - 팝업 애니메이션은 기존 UIView에 확장 구현되어있는 executePresentPopupAnimation() 함수의 애니메이션과 같이 구현하였습니다.   
  초기에는 해당 함수를 그대로 사용하고자 했으나,  
  애니메이션 시 배경이 변경되는 등의 애니메이션을 팝업 뷰의 애니메이션과 동시에 구현하기 위해서  
  애니메이션 코드를 별도로 작성하였습니다. 

### ❗️PR Point

- 앱 전체적으로 여러 뷰에서 팝업 창이 뜨는 상황인데,  
이를 UIKit의 UIAlertController와 같이 조금 편하게 쓸 수 있도록 하기 위해서 현재 새로운 브랜치를 생성하여 구현 중에 있습니다. 
해당 기능을 구현하면 후에 현재 코드를 새로운 기능으로 수정할 예정입니다. 
- 추가로 개선해야 할 부분
  - 홈 버튼이 있는 기종의 화면 비율에서는 하단의 사용방법이 버튼에 가려지는 문제가 있습니다.  
  추후 개선 예정입니다. 
  - 아이폰 mini 시리즈에서 UI가 의도대로 동작하는지 구현하기 위해 iPhone 13 mini 시뮬레이터를 돌려보았는데요,  
  팝업창이 뜨지 않는 문제가 있습니다. 
  아마 팝업이 뜰 때 키보드가 화면에 동시에 올라오도록 하는 과정에서 문제가 생긴 것으로 추정합니다. 
  이게 코드의 문제인지, 아니면 시뮬레이터의 문제인지 아직 정확히 모르는 상황이라, 조금 더 공부해보아야 할 것 같습니다. 
  ### 따라서 코드가 제대로 동작하는지 확인하기 위해서 테스트 시 실제 기기를 사용하는 것을 권장합니다.

### 📸 스크린샷

|뷰|설명|
|:------:|:---:|
|    |     |

https://github.com/user-attachments/assets/70369567-48f6-4528-8dac-01380b7cc927

- Resolved: #172

2024-09-15 12:52 UTC, codeJiwon requested changes

2024-09-15 12:52 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponCodeInputPopupView.swift
> +    private let popupTitleLabel = UILabel()
P5

변수명 제가 지었던 것보다 확실히 통일성 있고 깔끔하네요! 좋은 것 같습니다:)

2024-09-15 12:52 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
> +        $0.numberOfLines = 0
P5

아 description의 줄이 정해져 있지 않으니까 0으로 설정하는 게 맞았겠네요!! 하나 또 배워갑니다

2024-09-15 12:52 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponCodeInputPopupViewController.swift
> +    private func setupControlsTarget() {
P3

코드 컨벤션에 addTarget함수는 setupTarget()으로 하기로 했었는데 setupControlsTarget()으로 설정한 이유가 궁금합니다.

2024-09-15 12:52 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponCodeInputPopupViewController.swift
> +    private func setupPresentation() {
P3

setupStyle()이 아닌 setupPresentation()으로 설정하신 이유가 따로 있나요?

2024-09-15 12:58 UTC, codeJiwon approved these changes

2024-09-15 15:00 UTC, Johyerin approved these changes
고생하셨습니다!

2024-09-16 12:00 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponCodeInputPopupViewController.swift
> +    private func setupControlsTarget() {
혹시 코딩 컨벤션 어느 부분에 setupTarget()이 적혀있는지 알 수 있을까요~?
노션에 있는 Coding Convention 페이지에서는 찾을 수가 없네요...

addTarget() 은 UIControl의 메서드라서 UIControl들의 target을 설정한다는 의미로 setupControlsTarget이라고 메서드 이름을 정했는데, 다른 분들의 코드는 setupTargets라고 적혀있는 경우가 많더라구요
혹시 이 부분을 통일해야 한다고 생각하면 의견 주시기 바랍니다!

2024-09-16 12:00 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponCodeInputPopupViewController.swift
> +    private func setupPresentation() {
presentation과 관련된 속성을 설정하는 메서드이기 때문에 메서드 이름을 `setupPresentation` 이라고 했습니다. 
setupStyle은 이름에서 유추할 수 있듯, 스타일을 정하는 역할을 한다고 생각하여 
저는 `setupStyle()` 메서드를 각종 UI컴포넌트들의 스타일(텍스트 컬러, 폰트 등..) 설정을 하는 함수로 이해하고 있습니다.

2024-09-16 12:00 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
>      }
`setLineSpacing`나 `setLineHeight` 함수를 이용하여 행간을 설정할 경우 `attributedString`에 값이 할당되면서 기존의 UILabel의 textAlignment에 할당한 값이 적용되지 않는 현상이 생기는 것 같더라구요

177번 브랜치에서 이를 해결하였고,  177번 브랜치 PR을 머지하여 구현한 수정사항을 반영하면 아마 텍스트의 중앙정렬이 적용될 겁니다!

2024-09-16 12:15 UTC, merged