[Fix/#185] 회원가입 뷰 QA 수정사항 반영
Team-Offroad/Offroad-iOS pull request #195
Opened 2024-09-21 17:36 UTC by codeJiwon

### 🌴 작업한 브랜치
- #185 

### ✅ 작업한 내용

 - textfield 눌렀을 때 layer 검정으로 변경 -> 검정은 클릭과 텍스트 유무
 - textfield 미입력 후 키보드 내려가면 다시 회색이게 변경
- textfield 입력 후 다 지웠을 때 textfield에 커서가 있다면 layer 검정이게 변경
- 하나라도 오류가 있다면 에러메세지 계속 떠 있도록 수정
 - 오류 난 textfield의 layer는 다른 곳을 선택해도 .primary(.error)가 유지되도록 수정

```swift
//빨간 layer 유지하는 코드
if validateInputs() {
            birthView.nextButton.changeState(forState: .isEnabled)
        } else if !validateYear() || !validateMonth() || !validateDay() {
            //유효하지 않으면 빨간 layer 계속 유지
            if textField == birthView.yearTextField && !validateYear() {
                textField.layer.borderColor = UIColor.primary(.error).cgColor
            } else if textField == birthView.monthTextField && !validateMonth() {
                textField.layer.borderColor = UIColor.primary(.error).cgColor
            } else if textField == birthView.dayTextField && !validateDay() {
                textField.layer.borderColor = UIColor.primary(.error).cgColor
            }
            birthView.nextButton.changeState(forState: .isDisabled)
        }
```

### ❗️PR Point

실시간으로 유효성 검사가 되게 구현하는 게 어려웠다.
처음에 오류 났을 때, 수정하여 유효값이 된 후, 다시 유효하지 않은 값을 입력했을 때의 로직까지 생각해야했다.
@objc 함수들을 통해서 구현할 수 있었다.

### 📸 스크린샷

|뷰|설명|
|:------:|:---:|
|        |     |

- Resolved: #185

2024-09-22 11:44 UTC, nolanMinsung requested changes
코드보다는 동작에 문제가 있어 여기에 확인된 사항들 적어두겠습니다
아래 동작들은 사용자의 의도와 다르게 동작하거나, 기획에서 제시한 기준과 다르게 동작하므로, approve가 아닌 request changes로 리뷰를 작성하였습니다. 

### 닉네임 설정 뷰
- 글자 수 수정하기. (조건에 맞지 않음)
    - 최소 글자 수 EUC-KR 기준 4바이트로 설정하기.
    - "acdefg김김김김" 은 입력 가능해야 하지만, "abcdefg김김김ㄱ" 이후 추가 텍스트 작성 불가능함.
    
### 생년월일 입력 뷰
  - 월 입력 시 "1"이 아닌 "01" 과 같은 형식으로 입력하면 월 입력창 빨간 테두리 유지됨.
  - 일 입력 시 년 혹은 월 입력창이 비어있으면 일 입력창에 형식에 맞게 입력해도 빨간 테두리 유지함.
  - 키보드가 내려간 상황에서 마지막으로 입력했던 텍스트필드의 테두리가 여전히 진한 검은색을 유지함.
  
다음은 코드의 개선사항이지만, 이번 브랜치의 수정사항이 아니기 때문에 코멘트를 달 수 없어 여기에 적습니다. 
- `BirthViewController`에서 `setupAddTarget()` 함수(58-75)와 `setpTarget()` 함수(338-346)에 일부 겹치는 코드가 있는 것 같습니다. 

기타
- 함수 앞에 주석을 단 부분은 좋은 것 같습니다. 함수의 길이가 길어지면 이해하기 힘들 수 있는데, 적절한 주석은 함수의 의도를 설명하는 데 도움이 된다고 생각합니다. 
- PR 등을 작성 시에 "회원가입 뷰"와 같은 모호한 표현보다는 작업한 뷰(예, 생년월일 입력 뷰)를 명시하는 게 더 좋을 것 같다는 의견 남깁니다.

2024-09-22 11:44 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
>      }
이 함수의 용도를 알 수 있을까요?
어디에서도 호출되지 않는 함수입니다...

2024-09-22 12:14 UTC, Johyerin reviewed
고생하셨습니다! 🔥👍🏻

2024-09-22 12:14 UTC, Johyerin commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
> +    }
P4

textField의 delegate를 지정해주고 사용한만큼, 위쪽에 addTarget을 통해 추가해준 Objc 함수들의 역할 역시 delegate를 통해 편하게 구현해줄 수 있을 것 같아요! PR Point로 적어두엇던 실시간 대응에도 좀 더 유연하게 작성할 수 있을 것 같다고 생각합니당 한 번 살펴보고 리팩토링할 때 적용하는 등 발전시키면 좋을 것 같습니닷

2024-09-23 07:55 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
>      }
로직을 수정하다보니 삭제했어야 했는데 그대로 뒀네요! 삭제하겠습니다.

2024-09-24 04:45 UTC, nolanMinsung approved these changes

2024-09-24 07:18 UTC, merged