[Fix] #367 - 온보딩 약관동의 뷰 개선
Team-Offroad/Offroad-iOS pull request #373
Opened 2024-12-06 19:20 UTC by Johyerin

### 🌴 작업한 브랜치
- #367

### ✅ 작업한 내용

- 온보딩 약관 동의 뷰 팝업 로딩 시점 변경
- 온보딩 도중 이탈 시, 무조건 스플래시 이후 로그인뷰로 이동
- 마케팅 수신 동의 시 토스트 구현
  - 따로 디자인이 지정되어있지 않아, 기존에 구현되어있던 토스트를 사용하였습니다.

### 📸 스크린샷

|온보딩 이탈 시 재로그인|온보딩 팝업 로딩|
|:------:|:---:|
|<img src = "https://github.com/user-attachments/assets/5a686efe-835b-4236-afc4-213eefcc7e64" width ="250">|<img src = "https://github.com/user-attachments/assets/4ac31f02-b1b7-492e-b227-b4acc2ec31e4" width ="250">|

|마케팅 수신 동의 토스트((온보딩 뷰)|마케팅 수신 동의 토스트(설정 뷰)|
|:------:|:---:|
|<img src = "https://github.com/user-attachments/assets/9cc150a2-1276-4033-89b7-1f58b5552638" width ="250">|<img src = "https://github.com/user-attachments/assets/ad83fb1a-e251-4e61-969a-e61e43debdaf" width ="250">|

- Resolved: #367

2024-12-07 06:12 UTC, nolanMinsung requested changes
마케팅 수신 여부 팝업이 늦게 뜨는 대신 약관 내용은 끊김 없이 뜨는 점 확인했습니다!
수고하셨습니다!~ 👍
마케팅 수신 동의 API 요청 시 실패 케이스에 대해서 구현해야 할 것 같아, 관련 코멘트 남겨놓았으니 확인 바랍니다 :)

2024-12-07 09:30 UTC, codeJiwon approved these changes
수정사항 확인했습니다! 구현하느라 고생하셨습니다👍

2024-12-07 09:30 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/MarketingConsent/ViewController/MarketingConsentViewController.swift
>                  break
제안하신 네트워크 통신 해제 시 수정사항 확인했고 온보딩에도 해당사항 반영하도록 하겠습니다!

2024-12-08 07:06 UTC, nolanMinsung approved these changes
플러그인에서 바로 네트워크 에러 처리하는 방안 좋은 것 같습니다!

2024-12-08 07:07 UTC, merged