[Refactor] #389 - 온보딩 리팩토링
Team-Offroad/Offroad-iOS pull request #391
Opened 2024-12-20 07:22 UTC by codeJiwon

### 🌴 작업한 브랜치
- #389 

### ✅ 작업한 내용

1. 이벤트 처리
    @objc 메서드로 텍스트 필드의 상태 변화를 처리하는 부분에 RxSwift를 적용
2. 닉네임 유효성 검사와 상태 관리:
     RxSwift를 사용하면 UI 상태(버튼 활성화, 텍스트 필드 스타일)를 반응형으로 구현

1. 텍스트 필드 이벤트 처리:
    * editingDidBegin, editingDidEnd, editingChanged를 RxSwift로 처리하여 간결화.
2. 중복 체크 요청:
    * checkButtonTapped에서 Rx 기반 네트워크 요청 처리(subscribe(onSuccess:onError:)).를 통해 중복 체크를 요청하다.
4. 키보드 내리기:
    * UITapGestureRecognizer를 Rx로 바인딩했다.
5. 기존 분기처리에서 formError일 때의 에러 처리가 중복되었었는데, rxSwift를 통해 onError에서 바로 처리하면서 중복되는 부분을 발견할 수 있었다.

[정리]
- 텍스트 필드와 버튼 이벤트를 선언적으로 처리
- Rx 기반 네트워크 처리로 비동기 코드를 간결하게 함

### ❗️PR Point
389를 머지받았을 때의 충돌을 대비하여 rxSwift를 적용한 코드는 Re{기존VC이름}의 이름으로 새 파일을 만든 상태입니다.
주석처리 되어 있는 부분은 2차 qa 수정사항의 적용사항이 반영되지 않아 현재는 에러가 나는 코드들입니다. 
추후 389를 머지받고 나면 주석 해제할 예정입니다.
```
넣고싶은 코드가 있다면 적어주세요
```
-->

### 📸 스크린샷

|뷰|설명|
|:------:|:---:|
|        |     |

- Resolved: #389

2024-12-20 14:32 UTC, nolanMinsung requested changes
고생하셨습니다!
닉네임 입력 뷰에서 다음으로 넘어가는 버튼의 동작을 구현해 주셔야 할 것 같아요.
이 외에도 사소한 문제들이 발견되지만, 큰 문제는 되지 않을 것 같아, 나중에 천천히 수정하면 될 것 같습니다.

2024-12-20 14:32 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
> +    /// BehaviorRelay로 각 버튼 상태 관리
/ 세 개를 사용하여 마크업 주석으로 적은 이유가 있을까요?
코드의 의도를 설명하는 것이라면 / 두 개를 사용하는 것이 훨씬 목적에 맞아 보입니다.

2024-12-20 14:32 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/ReGenderViewController.swift
> +//  GenderViewController 2.swift
파일 삭제가 제대로 되지 않은 것 같습니다. 확인 부탁드립니다.

2024-12-20 14:32 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
>          self.modalPresentationStyle = .fullScreen
이 코드는 어떤 목적의 코드일까요? ReGenderViewController 객체가 present 되는 상황이 있는 걸까요?

2024-12-20 14:32 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
>  final class NicknameViewController: UIViewController {
P1
닉네임 뷰에서 다음으로 넘어가는 버튼의 동작이 구현되어있는 것 같지 않아, 온보딩의 다음 단계로 넘어갈 수 없는 것 같습니다. 
확인 부탁드립니다.

2024-12-20 20:05 UTC, Johyerin requested changes
고생하셨습니다! 리뷰 사항 + 닉네임 다음 뷰로 넘어갈 수 없는 문제 수정 부탁드려요!

2024-12-21 03:43 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
>  final class NicknameViewController: UIViewController {
수정 완료했습니다!

2024-12-21 03:43 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
>                  else if self.whetherDuplicate == false && self.formError(self.nicknameView.nicknameTextField.text ?? "") == false {
아!! 그러네요 닉네임 형식이 맞을 경우에만 중복 확인을 해야하니 삭제하도록 하겠습니다

2024-12-21 03:47 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
> +    /// BehaviorRelay로 각 버튼 상태 관리
알겠습니다! 목적을 고려하여 주석 사용하도록 하겠습니다

2024-12-21 03:50 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
>          self.modalPresentationStyle = .fullScreen
지우는 걸 깜빡했네요..! nextButton을 눌렀을 때 동작하는 함수인데 navigateToChoosingCharacter(gender: String?)로 구현해서 지웠어야 하는 코드입니다. 꼼꼼히 확인해주셔서 감사합니다👍

2024-12-21 04:23 UTC, nolanMinsung approved these changes
다음 버튼 기능 동작하는 점 확인했습니다.
수고하셨습니다!

2024-12-21 04:23 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
> +    @objc func buttonToBirthVC(sender: StateToggleButton) {
P2
이 메서드는 버튼을 눌렀을 때 새로운 뷰컨트롤러를 push하는 동작으로 보이는데요, 메서드 이름이 헷갈리는 것 같습니다. 
메서드 이름만 보았을 때는 속성 같아 보여서, push 하는 메서드임을 표현할 수 있는 메서드 이름이 좋을 것 같습니다.

2024-12-21 04:23 UTC, nolanMinsung commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
> +        }
해당 버튼은 push될 nextVC에서 보이는 뒤로가기 버튼인데, NicknameViewController 메서드 안에서 생성한 것 같습니다. 
혹시 뒤로가기 버튼을 버튼이 보일 뷰컨트롤러에서 구현하지 않고, push하는 이전 뷰컨트롤러에서 미리 생성하여 push되는 뷰컨트롤러에 넣는 이유가 있을까요?

2024-12-21 04:49 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
> +    @objc func buttonToBirthVC(sender: StateToggleButton) {
그럴 수 있겠네요! navigateToBirthViewController로 이름 변경했습니다👍

2024-12-21 04:55 UTC, codeJiwon commented on Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
> +        }
pushViewController를 호출할 때 navigationController를 통해 화면 전환이 되니까 네비게이션 바와 관련된 코드도 함께 처리하는 것이 더 자연스럽다고 생각했습니다. 하지만 민성님 의견을 들으니 BirthViewController에서 보여야하는 뒤로가기 버튼은 BirthViewController에 존재하는 게 더 직관적이겠다는 생각이 드네요! 해당 부분 수정하도록 하겠습니다.

2024-12-21 11:01 UTC, merged